language: python
python:
  - "2.7"

script:
  - python build.py

before_install:
  - openssl aes-256-cbc -K $encrypted_678d53392411_key -iv $encrypted_678d53392411_iv
  -in id_rsa.enc -out id_rsa -d

install:
  - "pip install ."
  - "pip install -r requirements.txt"

after_success:
    - "ls -las"
    - "scp -i id_rsa -r images assets index.html mbjerkness@bjerkness.net:~"

before_script:
  - echo -e "Host bjerkness.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
