before_install:
- openssl aes-256-cbc -K $encrypted_678d53392411_key -iv $encrypted_678d53392411_iv
  -in id_rsa.enc -out id_rsa -d
after_success:
    "scp -i id_rsa-r images assets index.html mbjerkness@bjerkness.net:~"
